# Generated by Django 4.0.8 on 2026-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_locked_attendance_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
