# Generated by Django 5.2.11 on 2026-02-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_summary_az_course_title_az_program_summary_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment_weight',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_weight',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='final_exam_weight',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='mid_exam_weight',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_weight',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
