# Generated by Django 5.2.11 on 2026-02-22 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_assignment_assignmentsubmission_delete_courseoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[(6, '6 Months'), (8, '8 Months'), (9, '9 Months')], default=6),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='courses',
            field=models.ManyToManyField(related_name='allocated_lecturer', to='course.course'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='course.program')),
            ],
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='course.classgroup'),
        ),
    ]
